### ISSUE TITLE
Request : sv_randomMapRotation dvar to allow random map rotation.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [XLabsProject/iw4x-client#105]
COD4x have sv_randomMapRotation dvar to allow random map rotation. It would be nice to have this in iw4x.
Alternatively, lobby support random map rotation. Unfortunately, lobby wont start game if there is only 1 player.
So far, there is noway to have random map rotation for 1 player. I play against bots(botwarfare).

Thanks for such a great work.

**Comment by Dss0** [comment]
Random map rotation for match servers sounds like a neat feature that should be considered, not super high priority right now tho.

**Comment by diamante0018** [comment]
Just to make sure I understand what you want @syaifulnizamyahya 
`sv_randomMapRotation` is implemented in CoD4x_Server inside the function that handles the `map_rotate` command. The map rotation is only randomized if `sv_mapRotationCurrent` Dvar is false.
It means that you would need to manually set `sv_randomMapRotation` to true and execute the command `map_rotate` by yourself. Is this what you want?

**Comment by Dss0** [comment]
Implemented in #146
