### ISSUE TITLE
Game runs out of memory after rotating the map a few times

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/iw4x-client#15]
After rotating the map a few times (5-10) the game will run out of memory. This also happens without having any mods loaded and playing on vanilla mw2 maps. My suspicion is that the custom content added by iw4x itself or mods is being loaded into memory when the map rotates but the previous loaded content is not unloaded/still persists.

**Comment by Dss0** [comment]
update and possibly related: There seems to be a huge memory leak in the implementation of custom menus, they are also never unloaded from memory.

**Comment by diamante0018** [comment]
Say no to memory drips

**Comment by Rackover** [comment]
https://github.com/XLabsProject/iw4x-client/pull/740
