### ISSUE TITLE
IW4X doesn't respect net_ip - Listens on TCP, not UDP

### ISSUE THREAD

**Issue by Ayymoss** [XLabsProject/iw4x-client#171]
Both Windows and Linux (WINE) are affected.

My dedicated server has multiple public IPs, binding on the secondary IP via `+set net_ip <x>` listens on TCP but you cannot connect in-game (UDP).

The intention is to bind on my secondary (floating) IP so if I upgrade/change service on my provider I don't lose the IP and people's favourites. 

Other services I run on the server respect IP binding correctly.

#### Windows Testing Method

* Assign secondary static IP to main NIC adapter via [Network and Sharing Centre](https://www.daktronics.com/en-us/support/kb/DD1990270)
* Added these arguments to start parameters `-dedicated +set net_ip XX.XX.XX.XX +set net_port XXXXX`
* Start the server. You should be able to see the server via the HTTP server, however, you should not be able to connect in-game.

#### Linux Testing Method

* Assign secondary static IP in your distro...
* Follow Windows testing method, but run via `wine`.
* Same result, accessible via HTTP, not in-game.

Update/Edit: You'll be able to see the HTTP server, but unable to connect to the game via the IP. It binds on the default or "primary" NIC address; which isn't the expected output/functionality of `net_ip`.

**Comment by RaidMax** [comment]
Investigated this on behalf of @MrAmos123. This is a multifaceted issue. 
1) IW4's `Sys_StringToSockaddr` is improperly setting up the `sockaddr->sin_addr` value when `net_ip` is supplied (Not sure where it's going wrong, but hooking and reimplementing this routine fixes the issue)
2) WINE compatibility on Linux is inconsistent when attempting to bind the socket with a `net_ip` specified (Ubuntu 20.04 with WINE 6 and WINE 5 fails, Debian 11 with WINE 6 also fails, but Debian 11 with WINE 5 or WINE 4 work.

**Comment by diamante0018** [comment]
I will attempt to debug `Sys_StringToSockaddr` to confirm where and what fails.

**Comment by MrAmos123** [comment]
Resolved in 0.7+.

**Comment by MrAmos123** [comment]
Nevermind. This isn't resolved. 

Test Environment: 
OS: Debian 10
Interfaces: 2, DHCP
Wine: 7

It fails to bind on a secondary IP address, however, binds correctly using Wine 4.

**Comment by diamante0018** [comment]
It is my understanding RaidMax provided you with a 'stub' that fixed the issue for you? Is this still persistent post 'fix'. 
Did you test on a clean iw4x.dll (stable)?

**Comment by diamante0018** [comment]
Update: Close this issue when the launcher is replaced by a new system/updater or completely removed and going to manual installs.

**Comment by diamante0018** [comment]
I got ideas now for this.

**Comment by diamante0018** [comment]
RaidMax got in contact with me and said this is a bug with wine. And it used to work on some old versions of that software probably because of even more bugs.
If it helps you can disable the mod download code using the documented command line.
Sorry but I don't feel responsible for fixing wine errors since this appears to be a bug with how they implement port binding on their end. I never interacted with the wine community but if they have a place where you can report bugs I'd try it.

**Comment by Swaluver88** [comment]
I don't think this she be closed as "not planned". To many users this should be fixed for security router/modem issues that vastly expands to different products
