### ISSUE TITLE
IntermissionTime is not configurable

### ISSUE THREAD

**Issue by H3X1C** [XLabsProject/iw4x-client#21]
iw4x_00.iwd\maps\mp\gametypes\_gamelogic.gsc Defines the intermission time period. This is currently hard coded(this is not ideal for server owners), also redundant foreach:
```
	if (!matchmakingGame())
	{
		foreach (player in level.players)
		{
			//player openPopupMenu("popup_summary");
		}
		
		intermissionTime = 30.0;
		
		if(getDvarInt( "party_host" ))
		{
			intermissionTime = 10.0;
		}
		
		thread timeLimitClock_Intermission( intermissionTime );
		wait intermissionTime;
	}
```
My suggestion would be this:
```
	if (!matchmakingGame())
	{
		
		intermissionTime = level.intermissionTime;
		
		if(getDvarInt( "party_host" ))
		{
			intermissionTime = 10.0;
		}
		
		thread timeLimitClock_Intermission( intermissionTime );
		wait intermissionTime;
	}
```
& then at the top of the gsc:
```
init()
{
	setDvarIfUninitialized( "scr_intermissionTime", 10 );
	level.intermissionTime = getDvarInt( "scr_intermissionTime" );
}
```
Attached file contains the aforementioned edits.
[_gamelogic.txt](https://github.com/IW4x/iw4x-client/files/3994861/_gamelogic.txt)

**Comment by RektInator** [comment]
Why not get the dvar value directly? I don't see the point of the step in between.

**Comment by RektInator** [comment]
scr_intermissionTime could just be added to the client code with 10 as default value, I don't see the point of that extra line of GSC

**Comment by H3X1C** [comment]
Ah you are correct my mistake, I made this as a workaround a while back to work with existing clients. So yes `setDvarIfUninitialized( "scr_intermissionTime", 10 );` should be removed if the client code get updated to set that dvar.

**Comment by H3X1C** [comment]
[_gamelogic.txt](https://github.com/IW4x/iw4x-client/files/3994926/_gamelogic.txt)
Updated gsc file with redundant line removed.
