### ISSUE TITLE
Bounce sounds on grenades and projectiles not working

### ISSUE THREAD

**Issue by H3X1C** [XLabsProject/iw4x-client#22]
```
        // Don't load bounce sounds for now, it causes crashes
        // TODO: Actually check the weaponfiles and/or reset the soundtable correctly!
        //Utils::Hook::Nop(0x57A360, 5);
        //Utils::Hook::Nop(0x57A366, 6);
        Utils::Hook::Nop(0x5795E9, 2);
```
Line 459 in Weapon.cpp grenades and projectiles do not make any sounds when they bounce off the ground. Claymores and other mines also do not make a plant sound because they use the bounce sound for that.

If `Utils::Hook::Nop(0x5795E9, 2);` is removed the bounce sounds work but the game crashes at the second match. As the code comments suggest I assume this just never got done, so would be nice to get sorted :)

**Comment by RektInator** [comment]
Feel free to fix it

**Comment by pvorisek25** [comment]
@RektInator I will try to fix it but I can be unsuccessful.

**Comment by pvorisek25** [comment]
I know that this is an "old" thread but I still booted up IW4x and the vanilla game recently to test the sound difference. But I didn't hear any "bounce sounds on grenades" in both vanilla game and IW4x. The claymores behave the same in both versions too. So I've checked the change log if the problem was solved, but these is nothing about this problem. So I've looked into the code and I found that there are still two commented out lines. I've decided to test if the crash still works (because why not) with the commented out lines and yes, the crash still works. The game crashes after first or second match. Am I missing something?

**Comment by H3X1C** [comment]
> I know that this is an "old" thread but I still booted up IW4x and the vanilla game recently to test the sound difference. But I didn't hear any "bounce sounds on grenades" in both vanilla game and IW4x. The claymores behave the same in both versions too. So I've checked the change log if the problem was solved, but these is nothing about this problem. So I've looked into the code and I found that there are still two commented out lines. I've decided to test if the crash still works (because why not) with the commented out lines and yes, the crash still works. The game crashes after first or second match. Am I missing something?

This only affects weapons loaded as raw files.

**Comment by pvorisek25** [comment]
> 
> 
> > I know that this is an "old" thread but I still booted up IW4x and the vanilla game recently to test the sound difference. But I didn't hear any "bounce sounds on grenades" in both vanilla game and IW4x. The claymores behave the same in both versions too. So I've checked the change log if the problem was solved, but these is nothing about this problem. So I've looked into the code and I found that there are still two commented out lines. I've decided to test if the crash still works (because why not) with the commented out lines and yes, the crash still works. The game crashes after first or second match. Am I missing something?
> 
> This only affects weapons loaded as raw files.

I am sorry, I don't know much about these things. Can you please describe how you can load a weapon as raw file?

**Comment by H3X1C** [comment]
Weaponfiles that are included in any mod. Just take the frag grenade weaponfile and put it into userraw/weapons/mp or mods/modname/weapons/mp
