### ISSUE TITLE
Custom fonts doesnt working

### ISSUE THREAD

**Issue by V3nilla** [XLabsProject/iw4x-client#238]
Hello. When i'm compiling font and loading it to the game, custom fonts doesnt working. It says - Loading fastfile mod.ff and nothing changed. I did it as indicated here - https://github.com/XLabsProject/iw4x-client/pull/88
My mod.csv -
```
font,fonts/consola
font,fonts/comic
```
What should I do to make the fonts work

**Comment by diamante0018** [comment]
To change the fonts showcased specifically in #88, you would need to hex-edit the exe.
Please seek help in the modding channel in the Xlabs discord for future problems related to modding the game.
