### ISSUE TITLE
Team Balance is broken

### ISSUE THREAD

**Issue by yolarrydabomb** [XLabsProject/iw4x-client#24]
It will show up the message but never does the job.

**Comment by Jawesome99** [comment]
To my knowledge, the issue lies in the GSC script. I looked at that a while ago when making my own team balancing script and noticed that it relies on a property on players that isn't set in some cases, though I was unable to test in which cases.
```c
// \maps\mp\gametypes\_teams.gsc
balanceTeams()
{
        // ...
	players = level.players;
	for(i = 0; i < players.size; i++)
	{
		/// this isn't defined half the time
		if(!isdefined(players[i].pers["teamTime"]))
			continue;

		if((isdefined(players[i].pers["team"])) && (players[i].pers["team"] == "allies"))
			AlliedPlayers[AlliedPlayers.size] = players[i];
		else if((isdefined(players[i].pers["team"])) && (players[i].pers["team"] == "axis"))
			AxisPlayers[AxisPlayers.size] = players[i];
	}
        // ...
}
```

**Comment by Dss0** [comment]
like emosewaj said, related to gsc scripts. Since this repo doesn't contain rawfiles i will close this issue.
