### ISSUE TITLE
Please remove iw4x.org in github repository.

### ISSUE THREAD

**Issue by sevi-kun** [XLabsProject/iw4x-client#247]
When i visit [iw4x.org](https://iw4x.org/), I only get a suspicious website..
Please remove the link from the github repository, if the website is not being maintained.

![image](https://user-images.githubusercontent.com/43034898/166634258-86d3d705-6fa6-46e4-9b25-e111c0751ae1.png)

**Comment by diamante0018** [comment]
URL was replaced with the official website [xlabs](https://xlabs.dev/)
Thanks for reporting!
