### ISSUE TITLE
Feature Request: COOP for Spec Ops missions

### ISSUE THREAD

**Issue by update-freak** [XLabsProject/iw4x-client#26]
Is there a way to play COOP without Steam?

**Comment by Jawesome99** [comment]
IW4x is MP only.

**Comment by update-freak** [comment]
ok

**Comment by update-freak** [comment]
Hi there,
is IW4x still only MP and SP and not COOP?
I would like to play local COOP with a friend.

**Comment by diamante0018** [comment]
You can, come to the xlabs discord for help.
There is info on how to do it there
