### ISSUE TITLE
Mod cannot load playerdadaread on server

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/iw4x-client#261]
On my iw4x zombies server, after the newest update it no longer lets me load the mod and the server gives an error saying "could not find menu `playerdataread`" the mod has the playerdadaread menu in a iwd in the ui_mp file and still does not seem to work. It also can't find the main file as well but I stopped getting that error, unless I load the mod manually into the iw4 game files. This mod use to work fine until the last update of iw4x.

**Comment by TheSoliderror** [comment]
![20220507_135253.jpg](https://user-images.githubusercontent.com/83806741/167266487-75b79523-2e03-4d1d-8725-3f9c1039fca0.jpg)

**Comment by Dss0** [comment]
that error has nothing to do with your mod not working. have you tried loading the mod on your client? we added a few functions to iw4x that  your mod also uses (check the changelog) so you may have to rename them or use ours.

**Comment by diamante0018** [comment]
xlabs members resources are better spent investigating real issue instead of reading ill formed reports like this one. The issue lies in your mod and unfortunately this is not the right place to discuss modding related issues.
