### ISSUE TITLE
[Feature Request] Server ping and FPS

### ISSUE THREAD

**Issue by ammadisleet** [XLabsProject/iw4x-client#273]
hello is is possible to add fps code and also connected server ping as current struct of ping only shows ping on private matches but when we connected to dedicated server that dosnt work.
```
  int clientNum = Game::CG_GetClientNum();
  Game::client_t* client = &Game::svs_clients[clientNum];
  auto* const ping_string = Utils::String::VA("Server Latency: %i ms", client->ping);
```
above code isnt working on dedicated server but only works on private match

**Comment by diamante0018** [comment]
Erm, ping does work. Just check your offsets against the one being used in SV_Status_f. No real issue here to be honest.

**Comment by diamante0018** [comment]
I don't know why you are trying to read the ping status as a client when joining a remote server but thinking about this you are reading it from the wrong structure. Also the FPS code? What is that you are taking about? The client can show the current FPS by changing a dvar value (cg_drawfps) to true.

**Comment by ammadisleet** [comment]
saw that but dont know how to use :(
