### ISSUE TITLE
[Bug] Can't unbind Sprint if it's been bound to the B key

### ISSUE THREAD

**Issue by JoelColby** [XLabsProject/iw4x-client#276]
I've just tried this with a fresh iw4x_config and had a few folks double-check to ensure they could replicate this issue.

Inside of Options -> Controls -> Movement
1. Set Sprint to the B key
2. Go back, so that the config file saves.
3. Now try to go back into Controls -> Movement and try to unbind Sprint by selecting it and hitting Backspace. IW4x will crash.

Is this somehow related to the IW-generated keybinds at the top of the config? It seems it only crashes when the key selected is "B" and you try to unbind it.

**Comment by Laupetin** [comment]
Issue was a reimplementation of the method that looks up keybindings for either controller or keyboard not respecting the exact implementation details of the original game's method.

Should be fixed next update.

Thanks for the report :)

**Comment by Laupetin** [comment]
In case you want to test it and you don't want to compile the project yourself, write me on discord for a test build
