### ISSUE TITLE
[Feature Request] Extend maximum length of map rotation

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/iw4x-client#282]
Map rotation is currently limited to 1024 characters in length, this isn't enough if for example you want to run a rotation with all maps (base + dlcs + iw4x dlcs) that switches game type every time the map rotates. This will become a bigger issue with new dlc maps being added later on.
I'd recommend upping this limit to at least 2048.

**Comment by diamante0018** [comment]
Adding a `good first issue tag` as it's a trivial task to add a new cfg optional file (plus new commands) to extend length of map rotation
