### ISSUE TITLE
[Issue] Aim assist still enabled.

### ISSUE THREAD

**Issue by califerben** [XLabsProject/iw4x-client#295]
Hello Iw4x staff,

I have a server running with sv_allowaimassist 0. Really this command does not work, a player with controller still has aim assist. Disabling this command on the client side does work, so something is broken within the code for the server to the client.

Please fix this issue as the aim assist is far from the console aim assist and also let the server owners disable it instead of having it enabled on the client side.

Now you have to use the gsc scripting method to disable it for the client in order for it to not work..

Thanks for reading

**Comment by MrAmos123** [comment]
Yep, same with NBS. We have it disabled on our servers yet the client doesn't reflect the server's dvar. 

We've implemented a work around with via GSC, but the server-side toggle doesn't work.

**Comment by Dss0** [comment]
did you update your rawfiles or just the dll? this dvar is handled via gsc. https://github.com/XLabsProject/iw4x-rawfiles/blob/develop/iw4x/iw4x_00/scripts/_aimassist.gsc

**Comment by Laupetin** [comment]
The serverside dvar `sv_allowAimAssist` does work with a gsc script. Make sure you updated your iw4x/iw4x_00.iwd serverside for updated iw4x scripts.
All occurrences of this problem were people not updating their server rawfiles so far.

**Comment by diamante0018** [comment]
What @Laupetin said. There is no issue. Give a thought or two as to why you are not following the advice provided in the guide "IW4x Server Install Guide" [xlabs.dev](https://xlabs.dev/support_iw4x_server)
