### ISSUE TITLE
X Labs Updater not working

### ISSUE THREAD

**Issue by cvalle96** [XLabsProject/iw4x-client#299]
Hello,

When I run the iW4x game, I get this window that does nothing, closes and does not update. 

![image](https://user-images.githubusercontent.com/38204164/172453104-07a1d4b1-7ad6-4f40-8a7d-c44c6b6afafa.png)

**Comment by diamante0018** [comment]
You may want to let it do its thing. People reported it took several minutes until the updating file process finished.
If that continues to fail you should seek help in the xlabs discord iw4x-support section.
This repository is for the client itself and not the launcher.
