### ISSUE TITLE
CI: Testing

### ISSUE THREAD

**Issue by ghost** [XLabsProject/iw4x-client#3]
I am currently trying to figure out whether there is a way to replicate what Jenkins does by building binaries without the tests for artifacts, and binaries with the tests for actually running the tests. Unfortunately this is currently done via a Premake Option instead of using project configurations, so this is not easily done via Matrix.

_Originally posted by @iw4x-dev-urandom in https://github.com/IW4x/iw4x-client/pull/1#issuecomment-533022489_

This may need a rewrite of the Premake configuration in order to allow AppVeyor to build a 4-configuration matrix. Plus we need to prepare an installation of MW2 files just in case. Also this does not cover Linux. This would make this issue a big effort to solve.

**Comment by diamante0018** [comment]
Closing this as it does not reflect the current state of the repository or how iw4x files are built and shipped.
