### ISSUE TITLE
[feature request] namespaces for custom builtins

### ISSUE THREAD

**Issue by mjkzy** [XLabsProject/iw4x-client#309]
just like https://github.com/fedddddd/t5-gsc-utils/commit/c4660665309419808de22804ed38c586ccbfdaba. would make scripts more organized imo and it's a nice addition

kinda one of those random features that you may be interested in doing sometime @diamante0018 ;)

**Comment by diamante0018** [comment]
No

**Comment by mjkzy** [comment]
lmao
