### ISSUE TITLE
Game no longer starts with Steam running

### ISSUE THREAD

**Issue by H3X1C** [XLabsProject/iw4x-client#31]
A recent steam update has resulted in the game no longer starting. Adding the -nosteam arg enables the game to start.

Steps to reproduce:
-Have an up to date version of steam running on your machine.
-Launch IW4x
-Splash image will show, then it will disappear

Steam version: 
![image](https://user-images.githubusercontent.com/42491989/83509306-23894c80-a4c3-11ea-86c1-f7a8c9227645.png)

**Comment by Dss0** [comment]
Has been fixed in #35
