### ISSUE TITLE
[feature request] variadic string gsc function

### ISSUE THREAD

**Issue by mjkzy** [XLabsProject/iw4x-client#310]
just like how https://github.com/fedddddd/t6-gsc-utils/blob/main/src/component/io.cpp#L63 does it

or, if ur feeling fancy, https://github.com/fedddddd/t5-gsc-utils/blob/main/src/component/string.cpp#L75

**Comment by diamante0018** [comment]
I honestly see zero benefits in adding the T6 version of va. GSC supports string concatenation already there is no need for a 'va' style function. The T5 version is way too overkill and handling format strings is not a simple thing.
GSC is supposed to be a simple scripting language I don't think there will be ever a legitimate need to format strings.
`scripting::variadic_args` is just a fancy wrapper for iterating over the currently in-params.
Fed can do whatever he wants in his plugins, I am also a fan of his code, but this is just unnecessary as for the actual GSC scripts nothing would change.

**Comment by diamante0018** [comment]
I got word that Scr_ConstructMessage is already variadic.
I guess this settles it.
