### ISSUE TITLE
Bug: ingame camera/view flicks randomly

### ISSUE THREAD

**Issue by timon122** [XLabsProject/iw4x-client#314]
The first person view is flicking randomly to one side. 
This happens in private lobbies and public servers. 
Video of this bug is linked at the end.

Hardware Specs:
- CPU: Intel i7 6700K
- RAM: 16GB
- GPU: Nvidia GTX 1080
- Mainboard: ASUS Z170

Things I tried:
- lowering polling rate of my mouse (no change)
- changed to another mouse (same behavior)
- changed refresh rate of the monitor (no change)
- reinstalled iw4x with the launcher (no change)
- installed iw4x on another hard drive (no change)
- disabled Nvidia Overlay (no change)
- disabled gamepad support (no change)

Ingame footage of this bug: https://youtu.be/TeHJ2iVpYeY

Thanks for your support in advance.

**Comment by diamante0018** [comment]
Can you try to disable `m_rawinput` ? Just a thought.
To do so I suggest you open the console using `~` then type `\m_rawinput 0` then restart your game to make sure the changes apply then see if you still get this bug.

**Comment by timon122** [comment]
> 

Thank you so much!
This resolved the flicking of the camera.

**Comment by timon122** [comment]
I use a roccat kone aimo. The 2nd mouse I tried was a standard logitech wireless mouse.
Does this answer your question?

**Comment by JoelColby** [comment]
Just another piece of information to contribute to this discussion (not sure if it will be helpful).

A user reported a similar problem on the X Labs Discord this afternoon and it was also resolved by disabling raw input. They had a Razer Basilisk V2.

**Comment by diamante0018** [comment]
Thanks for providing the additional information @timon122. We will keep in mind this is an issue and if needed attempt to fix the component that handles raw input
