### ISSUE TITLE
Toast notifications do not work anymore

### ISSUE THREAD

**Issue by diamante0018** [XLabsProject/iw4x-client#317]
After the scheduler pull request was merged (#254) the toast notifications were accidentally disabled

`Scheduler::OnGameInitialized(Toast::Handler, Scheduler::Pipeline::RENDERER);` (`Toast::Toast()` function)

This causes the function `Handler` to be only called once meaning the queue of the toast notification is not getting processed.

Any attempt to now replace `OnGameInitialized` with `Loop` meaning the handler would be executed every renderer frame (`R_EndFrame`) will now crash the game every time a new Toast notification is added to the queue.
Attaching the debugger proves useless and the stack trace I get is basically empty.

My attempts to do something about this can be seen in this branch in my fork
[diamante0018/toast-test](https://github.com/diamante0018/iw4x-client/tree/toast-test)

**Comment by mjkzy** [comment]
i think you meant to redirect to [this](https://github.com/diamante0018/iw4x-client/tree/toast-test)
