### ISSUE TITLE
Steam crashing

### ISSUE THREAD

**Issue by IceNinjaman** [XLabsProject/iw4x-client#32]
https://github.com/IW4x/iw4x-client/blob/23e9aa7ac0107a3a7a8c7cda2de4287f127a871d/src/Steam/Proxy.cpp#L178

Must be now:
Proxy::ClientUser.invoke<bool>("SpawnProcess", ourPath, cmdline.data(), ourDirectory, gameID.bits, mod.data(), Proxy::AppId, 0, 0);

If you want to do that in a more smarter way you create a new thread, install a signal handler, do the Steam-Init, return from thread and remove the signal handler. So game can not crash when Steam-Init does crash.

Greetings CoD4x-Team

**Comment by Dss0** [comment]
Late answer but thank you for the fix, has been implemented.
