### ISSUE TITLE
sv_mapRotationCurrent does not get applied after new update.

### ISSUE THREAD

**Issue by efinst0rm** [XLabsProject/iw4x-client#326]
Hi,

After updating to 0.7.3 sv_mapRotationCurrent no longer gets applied once the game ends and map rotates. The dvar gets set "sv_mapRotationCurrent" is: "map mp_highrise" default: "" Domain is any text.

Seems the functionally got removed here https://github.com/XLabsProject/iw4x-client/commit/a4da5b891eff8c6f455fe96f7abd36b2c0f3d712#diff-0819ff5bf0d5f868811dd023b1dbeaf9aeb0e06fe05ef7b8a103048f8ac5e18aL163

**Comment by K-Faktor** [comment]
My Linux server does not change the map after updating the server to 0.7.3

**Comment by diamante0018** [comment]
This is expected behaviour. Because of the new update the only dvar uses is sv_maprotation.
Additionally in the server.cfg you can use addmap and addgametype to add new gametypes and maps to the rotation bypassing the 1024 limit string dvar have.
