### ISSUE TITLE
setName and resetName functions don't work in S&D

### ISSUE THREAD

**Issue by simonediberardino** [XLabsProject/iw4x-client#327]
Not sure if this is a known issue but the new setName and resetName gsc functions do not work when the game mode is search and destroy. Everything works fine when it's team deathmatch or free for all though. We have the exact same issue on IW5, the author of both the codes is the same so I suppose there's something wrong in the code.

**Comment by diamante0018** [comment]
Have you reported the issue to fed?

**Comment by simonediberardino** [comment]
Yeah Raez did that some months ago about his IW5 plugin but it has never been fixed

**Comment by diamante0018** [comment]
Call from GSC SetClientNameMode( "auto_change" );
