### ISSUE TITLE
Game prioritizes animations from common_mp (a fix would be nice)

### ISSUE THREAD

**Issue by GeroCOD** [XLabsProject/iw4x-client#384]
Any other cod that supports modding has the ability to edit these and create custom animations EX - COD4, COD WAW, BO1 ETC.
IW4X has no way of doing this it would be a nice feature to add to support custom animations like the other CODs

**Comment by diamante0018** [comment]
This was fixed not too long ago ( IW4x v0.7.4 ).
Make sure you put `playeranim.script` and/or `playeranimtypes.txt` in an IWD (zip archive renamed to .iwd) and iw4x will load it just fine. Or you should be able to drop it in the `userraw` folder as well.
Use the iw4x-modding channel to get help with this issue.
