### ISSUE TITLE
[ZoneBuilder] Use Team Zones for custom Maps

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/iw4x-client#397]
Currently custom maps ported via iw3exp/zb don't have useteamzones set in their arena file. it should either be set in the arena file or all maps loaded from usermaps should cause team zones to be loaded by default.

**Comment by Rackover** [comment]
It's done already, we just need to release latest iw4x mod builder and the issue will be fixed. It's fixed in the mod builder
