### ISSUE TITLE
[Feature request] Gamemode Kill Confirmed (MW3) and Gun Game (MW3)

### ISSUE THREAD

**Issue by update-freak** [XLabsProject/iw4x-client#398]
Hi devs,

please add the gamemode Kill Confirmed (MW3) and Gun Game (MW3) in further IW4x updates.
I love to play theses gamemodes and I think they should implemented in IW4x.
As far as I know they were part of React MW2 before.

**Comment by diamante0018** [comment]
There are already existing mods for these two gamemodes. There is currently no interest to integrate these mods in iw4x-rawfiles but that might change. You could work on them and open a pr to our rawfiles repository if you'd like.

**Comment by update-freak** [comment]
ok, thanks. Can you provide a links to the existing mods that I can load in the mods menu?

**Comment by diamante0018** [comment]
No, I can't. I do not sponsor any mod (except a select few I approve).
You must use google or any search engine you prefer to find them : P
