### ISSUE TITLE
[Feature Request] Master Server Blacklisting

### ISSUE THREAD

**Issue by MrAmos123** [XLabsProject/iw4x-client#426]
**What problem will this solve?**
Manual bans for people who find the need to server spoof to gain an attractive edge in the server browser. (RepZ, GodSend, SAN)

GodSend is the biggest culprit. RepZ needs to be warned about their bots acting as players. 

**What might be a solution?**
Manual blacklisting for abusive server owners.

**What other alternatives have you already considered?**
N/A

**Anything else we should know?**
I raised a thread in Discord about 2 weeks ago related to this problem. It doesn't look like anything is being done about it. (At least I couldn't find any commits related) 
So here's my frustration feature request.

There is no reason for these manipulative actors to be rewarded with effectively the entirely IW4x player pool. 
If nothing gets done about it, it shows that we can do it for our servers. 👍

**Comment by mxve** [comment]
https://github.com/XLabsProject/master/pull/300

**Comment by MrAmos123** [comment]
Ah, it's a separate repo, my apologies!

**Comment by MrAmos123** [comment]
Since it's active in development and unrelated to this repo I'll close this.

Thanks!
