### ISSUE TITLE
[Feature Request] Get Screenshot from Clients

### ISSUE THREAD

**Issue by MrAmos123** [XLabsProject/iw4x-client#436]
**What problem will this solve?**
Allow us to get a screenshot from a client's perspective. 
Allowing us to very quickly determine if someone is cheating.

Very similar to CoD4x's implementation would be awesome.

**Comment by Dss0** [comment]
way too intrusive.

**Comment by Rackover** [comment]
extremely easy to bypass, extremely intrusive too!

**Comment by shit-ware** [comment]
Terribly intrusive, among it possibly violating GDPR.
