### ISSUE TITLE
Cannot activate developer console

### ISSUE THREAD

**Issue by akgh11** [XLabsProject/iw4x-client#465]
`set sv_maprotation "gametype war map mp_afghan map mp_subbase map mp_overgrown map mp_compact map mp_overgrown map mp_strike map mp_subbase map mp_cargoship_sh map co_hunted map mp_favela map mp_cargoship_sh map mp_nightshift map mp_cargoship map mp_estate_tropical map mp_checkpoint map mp_cross_fire map mp_cargoship map mp_subbase map mp_brecourt map mp_afghan map mp_shipment map mp_crash_tropical map mp_storm map mp_quarry map mp_terminal map iw4_credits map mp_compact map mp_highrise map mp_highrise map oilrig map mp_rust map mp_compact map mp_trailerpark map mp_cargoship_sh map mp_trailerpark map mp_boneyard map mp_terminal map mp_fav_tropical map iw4_credits map mp_boneyard map mp_afghan map mp_estate map mp_complex map mp_vacant"`
`set fs_game "mods/bots"`
`set bots_manage_fill "100"`
`set bots_skill_max "6"`
`set sv_randommaprotation "1"`
`set sv_maxclients "100"`
`set sv_privateclients "0"`
`set party_maxplayers "100"`
`set thereisacow "1337"`
`set developer "1"`
`set sv_cheats "1"`
`set setmonkeytoy "1"`
`bind "``" "toggleconsole"`

**Comment by diamante0018** [comment]
Hi, there a few disclaimers when you open an issue. There is one in particular that specific that the right place to get help with getting the client to run is the xlabs discord where there is a support section you can get help. There is an invite link on the xlab's website

**Comment by akgh11** [comment]
@diamante0018

Is the discord server regularly backed up?

I thought something like Discord would go against the decentralization motto of this project.

I see many people in the discord have asked about the same issue I am having. No useful responses.
