### ISSUE TITLE
Playing iw4x no longer increments playtime hours in MW2-MP on steam

### ISSUE THREAD

**Issue by m1cr0man** [XLabsProject/iw4x-client#484]
**What are you trying to do?**
I am trying to get Steam to track the number of hours I am spending in iw4x as MW2 Multiplayer. 

**What problem are you having?**
This stopped working about a year ago if I remember correctly. The steam overlay works correctly. The game is detected as MW2 Multiplayer and the time in my current session increments but the past 2 weeks and total time do not change.
Also, Steam shows me as not in game, just online. This is related I imagine?

**What have you tried so far?**
Verified the game on steam. I tried moving the game to another folder and point the iwx launcher at that too to no avail.

**What version of IW4x are you using?**
0.7.5

**Anything else we should know?**
Windows 10. Nothing else I can think of.

**Comment by diamante0018** [comment]
Will probably never fix as steam support as a whole is scuffed and doesn't always work on its own when Steam is opened.

**Comment by m1cr0man** [comment]
Oh, well that's a shame. For my own knowledge, is the playtime tracker working for yourself/most people? At least I'd know whether I should continue trying to fix it locally.

**Comment by diamante0018** [comment]
No, apparently these things stop working when Steam changes its internal API. At least that is my own understanding.

**Comment by m1cr0man** [comment]
Alright thanks for the info!

**Comment by Rackover** [comment]
Don't close it ??? You can label it as wontfix if you won't fix it. This is an ongoing issue so it should be tracked. Otherwise other people will create it again.

**Comment by diamante0018** [comment]
Fixed in #573
