### ISSUE TITLE
[Bug] Party Server Implementation is broken

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/iw4x-client#499]
Party servers do not work properly on IW4x. The Issue is they are not visible on the serverlist or respond to connection attempts while sitting in the lobby, everything works fine when a map is running. When a map is running you can join and after the match ends you end up in the lobby, however as soon as you leave you can't join back as the server is not visible anymore.

We could either remove this feature altogether as almost nobody uses it (might be because it doesn't work) or fix it. I personally like this feature.

**Comment by Dss0** [comment]
Issue isolated to #445

**Comment by diamante0018** [comment]
Code for heartbeat is in the dedicated module
