### ISSUE TITLE
[Bug] G_FindConfigstringIndex: Overflow by Frequent createFontString Updates

### ISSUE THREAD

**Issue by MrAmos123** [XLabsProject/iw4x-client#589]
**What are you trying to do?**
Update on-screen elements for everyone for GunGame.

**What problem are you having?**
On-screen updated text elements using `createFontString()` too frequently over an extended game will restart the game due to an index overflow. `G_FindConfigstringIndex: overflow...`

Reducing the number of on-screen text elements prolongs the gameplay. However, will still crash if the game ends up being long enough.

I'd say 90% of our games currently play and end fine, but that 10% will end with the crash (logs attached), which will kick everyone for the same error as the top line of the log, including whatever on-screen message, triggered the overflow. 

```c
// Rendering for the Weapon Text:
WeaponHud()
{
    self.weaponhud = self createFontString("default", 1.5);
    self.weaponhud setPoint("TOPLEFT", "TOPLEFT", 6, 110);
    self.weaponhud.glowColor = (0.3, 0.3, 0.3);
    self.weaponhud.glowAlpha = true;
    self.weaponhud.hideWhenInMenu = true;
}
```
```c
WeaponNumber()
{
// Code snippet removed - this is just to show the flow of how the text is updated
    while (1) {
// self.weapon is updated elsewhere.
        self.weaponhud setText("^5Weapon: ^4" + self.weapon + "/" + (level.weapon.size - 1) + "\n" + extraText);
    }
}
```

Relevant logs with the crash: [console_mp.log](https://github.com/XLabsProject/iw4x-client/files/10087650/console_mp.log)
Please let me know if you want the full log. I cut this down to include the start of the crash and the end of it.
No related minidumps. 

**What version of IW4x are you using?**
0.7.6 (Tried with all newer versions from and including 0.54)

**Anything else?**
To clarify, if necessary, this problem only really occurs with high-player count and long-runtime games. It seems to be a nice game of _which will end first_, the array(?) or the match. :)

Apologies if the root problem is something else. I've attributed it to `createFontString` being at fault, I may be entirely wrong here.

**Comment by mjkzy** [comment]
the workaround for years has to do "overflow fixes" which clear the string table after a certain amount of strings are set via settext. a solution in client would be cool, but if you need a workaround, look into overflow fixes for gsc.

**Comment by MrAmos123** [comment]
Update. You can recreate it with this script.
In-game result: ![image](https://user-images.githubusercontent.com/4959320/203876766-c4c44d34-a42a-4e1d-87b4-59a92982bd1a.png)
Log from my run: [console_mp.log](https://github.com/XLabsProject/iw4x-client/files/10087730/console_mp.log)
GSC to replicate it: [_crashTest.txt](https://github.com/XLabsProject/iw4x-client/files/10087731/_crashTest.txt)
