### ISSUE TITLE
Error 0xC0000005 with iw4x 0.6.1

### ISSUE THREAD

**Issue by beyerleinf** [XLabsProject/iw4x-client#64]
So my game wouldn't launch anymore since today so I decided to download all the files again. But even with a fresh install I'm getting error 0xC0000005 on launch. I've attached the dumps :) I've tried both using a copy of the Steam version and the iw4x-full-game download you provide.

[minidumps.zip](https://github.com/XLabsProject/iw4x-client/files/5936835/minidumps.zip)

**Comment by mvivaldi** [comment]
I can confirm this, the problem is the new version of the steam client. If you close steam iw4x don't have any problem.

**Comment by Dss0** [comment]
IW4x needs a proper steam implementation so it doesn't break (or atleast doesn't crash) whenever steam changes their interfaces.

**Comment by beyerleinf** [comment]
If you have any advice on how to get started with this, I'd be down to help. Just not familiar with where to get started

**Comment by FragsAreUs** [comment]
steam integration just needs to be re wrote for the client

**Comment by Dss0** [comment]
fixed in #305
