### ISSUE TITLE
dvar camera_thirdPerson doesn't change value on dedicated server (cheat protected?)

### ISSUE THREAD

**Issue by upl1nk-v01d** [XLabsProject/iw4x-client#69]
I had an issue setting dvar camera_thirdPerson to 1 on dedicated server with latest compiled source code, using to set along with scr_thirdPerson to 1.
Setting dvar scr_thirdPerson to 1 on running dedicated server, client viewpoint on another pc with latest compiled code does not change. When I checked camera_thirdPerson on client console, the value stays to value 0, however running console command 'scr_thirdPerson 1' on usual server via "Create Game" and restarting match - dvar value stays to 1 and client viewpoint also changes.
Btw, how did you find right bite code to un-cheat dvar camera_thirdPersonCrosshairOffset? I didn't find right one.

**Comment by OneFourOne** [comment]
I don't understand what you're saying. This isn't controlled by the server, it's controlled by the client. This works fine.

**Comment by OneFourOne** [comment]
When setting scr_thirdPerson 1 by default it sets camera_thirdPerson 1, this isn't changed by the client.

**Comment by upl1nk-v01d** [comment]
Ok, I will make it clearer saying that setting dvar scr_thirdPerson to 1 on running **dedicated** server (not with "Create Game"), client viewpoint on another pc with latest compiled code (0.6.0 version with or without --ac-disable) does not change, but with 0.6.1 standart version - changes, except camera_thirdPersonCrosshairOffset (cheat protection issue #67).

**Comment by upl1nk-v01d** [comment]
> When setting scr_thirdPerson 1 by default it sets camera_thirdPerson 1, this isn't changed by the client. This is meant to be cheat protected.

Not sure, why I don't see here you latest post, but I'm posting some images: 
[http://v01d.rf.gd/info/141/client_on_another_pc_1.jpg](url)
[http://v01d.rf.gd/info/141/client_on_another_pc_2.jpg](url)
[http://v01d.rf.gd/info/141/dedicated_srv_console.jpg](url)
[http://v01d.rf.gd/info/141/dedicated_srv_settings.jpg](url)

**Comment by mjkzy** [comment]
is this still a issue or is this solved?

**Comment by upl1nk-v01d** [comment]
yes, it is.

**Comment by upl1nk-v01d** [comment]
it's an issue.

**Comment by mjkzy** [comment]
I believe camera_thirdPersonCrosshairOffset is cheat protected because the client is suppose to have that modified by the server? If that's the case, then I don't see why it should be un-cheat protected. Other than that, I think if IW4x gets another update, this issue should be fixed as #68 unlocks the dvar.

**Comment by upl1nk-v01d** [comment]
let's hope that could be that case.
btw, thanks for info.

**Comment by Dss0** [comment]
Addressed in #68
