### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by Ondrejko** [XLabsProject/iw4x-client#70]
I really dont know if it was IW4X or some weird stuff on my computer processes, but I heard this and only this even when I left the server. (Attached below)
Even though another player said "I think I hear chapchap", which would mean its a server issue, but I posted it here just to make sure.
The audio is really quiet, so you have to listen closely

https://user-images.githubusercontent.com/79742613/113486317-5f5dbb80-94b2-11eb-9a7a-9806920f9a2f.mp4

**Comment by Dss0** [comment]
Have not been able to reproduce this (and have never had this issue at all), chances of fixing such a random bug are probably pretty low.
