### ISSUE TITLE
Bitdefender shows a virus

### ISSUE THREAD

**Issue by GKid94** [XLabsProject/iw4x-client#72]
Bitdefender shows a virus in the IW4x file

![Screenshot 2021-04-16 030421](https://user-images.githubusercontent.com/18757054/114957170-bffcd900-9e60-11eb-9a34-0d96110e731c.jpg)

**Comment by Dss0** [comment]
False positive, exclude it from scanning.
Not really the correct place to post this tho, iw4x-updater is not open source and isn't part of this github repo.
/closed

**Comment by GKid94** [comment]
Ok I already sent the file to Bitdefender as false positive
