### ISSUE TITLE
g_gametype issue

### ISSUE THREAD

**Issue by upl1nk-v01d** [XLabsProject/iw4x-client#73]
Hi! I'm encountering issue with dvar g_gametype switching.
When loading map with gamemode Sabotage via command line, gametype switches to Team Deathmatch mode (first video link).
Otherwise, when launching with 'Create Game' - no issues.
Playing sab gamemode on dedicated server also I'm encountering very strange issue with scoring (second video link).

Please see video link below:
http://v01d.rf.gd/info/141/iw4x_gametype_issue.mp4
http://v01d.rf.gd/info/141/iw4x_gametype_issue_2.mp4

My server config settings: 
http://v01d.rf.gd/info/141/iw4x_server.cfg

**Comment by Dss0** [comment]
First issue isn't related to the client code, maybe your mod? 
Can you explain the second issue ("scoring") in more detail?

**Comment by upl1nk-v01d** [comment]
In my second video in top left corner the sabotage scoring system goes wrong.
It counts kill or deaths to somebody, I'm not sure, but something is wrong.

My mod's content is official bot warfare iwd package and server.cfg file.
I tried to launch and play without mods, but no difference.

**Comment by upl1nk-v01d** [comment]
Ok, I did another tests.
1. with my mod and bots: http://v01d.rf.gd/info/141/iw4x_gametype_issue_w_mod_bots.mp4
2. without my mod and bots: http://v01d.rf.gd/info/141/iw4x_gametype_issue_no_mod_no_bots.mp4
3. create game with my mod and bots: http://v01d.rf.gd/info/141/iw4x_gametype_create_game_w_mod.mp4

I do not understand, what is causing that issue.

**Comment by Dss0** [comment]
both sounds like script issues, try deleting /maps/mp/gametypes/sab.gsc in iw4x_00.iwd.
Anyways this simply doesn't belong here, maybe ask on discord.

**Comment by upl1nk-v01d** [comment]
well.. big thanks for help.

**Comment by upl1nk-v01d** [comment]
I did what you mentioned.
I even tried redownloaded clean version in win10 without any mods, but issue is still present. That sucks!
Anyway, you are doing great job, so thanks!

**Comment by upl1nk-v01d** [comment]
Dss0, you're right! :)
The sab script 'new' scoring system was totally screwed up.
I already fixed this by remastering script to COD4x scenario.
I'm happy with iw4x! :)
