### ISSUE TITLE
As soon as I change the resolution the game crashes

### ISSUE THREAD

**Issue by Gerrilicious** [XLabsProject/iw4x-client#78]
Title should explain the problem.

Any ideas what could be the issue?

What information could help solve the issue let me know.

Kind regards
Gerry

**Comment by Dss0** [comment]
The game sometimes fails to restart the directx device properly - reason unknown.
Change the resolution in the config file instead (players/iw4x_config.cfg).

**Comment by Gerrilicious** [comment]
Thx helped! still had too much problems with controller uninstalling now...
