### ISSUE TITLE
Script compile error with map Mission (MW3 map, DLC for 0.7.8)

### ISSUE THREAD

**Issue by update-freak** [XLabsProject/iw4x-client#845]
Hello,

after adding the new DLC for 0.7.8 with the MW3 maps, I got this error when I try to create a match with the map "Mission". All other MW3 maps can be load without an error.

Does anyone know how to solve it?
(also asked in Reddit: https://www.reddit.com/r/IW4x/comments/11uj5e9/script_compile_error_with_map_mission_mw3_map_dlc/)

![mission error](https://user-images.githubusercontent.com/40196995/226100810-761632eb-5312-4146-a337-221dbe079f5e.png)

**Comment by Rackover** [comment]
i submitted a fix on iw4x-rawfiles, it's on the way

**Comment by diamante0018** [comment]
It was fixed moments ago.
https://github.com/XLabsProject/iw4x-rawfiles/releases/tag/v0.1.4.
Run the Xlabs launcher to automatically acquire it or simply download it manually.
