### ISSUE TITLE
[Feature request] Support loading/converting old IW4M/aIW player stats

### ISSUE THREAD

**Issue by treybrisbane** [XLabsProject/iw4x-client#85]
Yo!

It'd be great if there was a way to load (or convert) my old IW4M/aIW player stat files. I have a bunch of backups of `iw4_md202ef8d_*.stat` files, but I'm unable to get any to load.

Here's an example stat file: [example stat file.zip](https://github.com/XLabsProject/iw4x-client/files/6645571/example.stat.file.zip)

Cheers!

**Comment by OneFourOne** [comment]
Loading stats from other clients isn't possible because IW4x has custom weapons which means there's different stats tables. I don't really think this would be helpful, especially when there's a bunch of new comers that have never used the older clients.

**Comment by treybrisbane** [comment]
>Loading stats from other clients isn't possible because IW4x has custom weapons which means there's different stats tables.

Yeah I figured as much.

>I don't really think this would be helpful, especially when there's a bunch of new comers that have never used the older clients.

I agree that it's a bit of a niche request. I raised this as kinda a last resort after spending way too many hours today attempting various methods of porting over my old stats. 😅 I'm not sure of the difficulty involved, but if you don't think this feature is worth it, then no worries.

**Comment by Dss0** [comment]
A very niche request, i don't think alot of people still have aIW stats files 9 years after it shut down. Won't be implemented, sorry.

**Comment by treybrisbane** [comment]
All g - understandable! 🙂
