### ISSUE TITLE
End of match challenge completion screen appears blank

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/iw4x-client#855]
**What are you trying to do?**
Have the end game challenge completion screen appear as normal. 

**What problem are you having?**
The end game challenge screen, the one that pops up right at the end of a match if you completed a challenge, appears blank.  

**What have you tried so far?**
Fresh install of IW4x and server. Tweaking server settings. 

**What version of IW4x are you using?**
0.7.8

**Anything else we should know?**
Not really, just a visual bug as far as I can tell. This issue appears on my Dedicated Lobby server
![20230320_160112](https://user-images.githubusercontent.com/77655611/226457656-02406ad8-da1a-48a1-82e5-1f7ba535fcea.jpg)

**Comment by diamante0018** [comment]
Cannot reproduce it on my party server running vanilla IW4x files.

**Comment by diamante0018** [comment]
Hello again. I believe to have found the problem after some digging. This has actually nothing to do with the game client but is rather a modding question. Feel free to contact us in the modding channel of the XLabs discord

**Comment by BoxOfMysteriez** [comment]
Thank you for the clarification. Bot Warfare is the only mod I'm running so I guess it has something to do with that
