### ISSUE TITLE
DX9->DX11

### ISSUE THREAD

**Issue by Swaluver88** [XLabsProject/iw4x-client#894]
_Before opening a new feature request, please see [Issues](https://github.com/XLabsProject/iw4x-client/issues) and check that a similar issue does not already exist.
If this a new request, help us help you by filling in the template below._

**What problem will this solve?**
Access to more functions and offloads of any uncessary gpu usage making the game more smoother and catch up with time.

**What might be a solution?**
Don't have a solution but I do have a lead/reference for this possible feature request. 
https://www.mtbs3d.com/phpbb/viewtopic.php?t=26340

**What other alternatives have you already considered?**
Haven't looked as far as alternatives to represent dx9 other than a source code that emulates dx11

**Anything else we should know?**
N/A

**Comment by diamante0018** [comment]
Thanks for your interest but this is not the scope of this project. However you are more than welcome to do this yourself.

**Comment by diamante0018** [comment]
I checked out that article you linked and it appears that is something almost restrictly reserved for games that have "issues". I can assure you IW4, so far, has no issues that I can think of related to Direct X and runs smoothly. I don't see how this can bring an improvement at all at this point.

**Comment by Rackover** [comment]
I have implemented a D3D12 wrapper on IW4x on another branch using the D3D9on12 API from Microsoft. It works. But it doesn't bring anything really useful as far as I can tell, and it also cuts down performance by a factor of 3 or 4.  I would go from having 400 FPS on highrise to having something like 80 FPS.
