### ISSUE TITLE
Custom menus broken

### ISSUE THREAD

**Issue by ghost** [XLabsProject/iw4x-client#9]
Got to know about this through @RektInator. It seems the current menu code which introduces support for compiling menus into fastfiles breaks custom game menus.

Custom menus seem to work fine under any of these conditions:

- Menus are script menus and are precached.
- Menus are packed into IWD

Current intention is to roll back these changes.

**Comment by RektInator** [comment]
I will pick up this issue later today

**Comment by icedream** [comment]
Internal team discussion: IW4x data repository will need a commit reverted that updates the list to compile the menu files into the fast files before this code can be bundled with the data assets.

**Comment by iw4x-dev-urandom** [comment]
Internal team discussion: A commit that updates the list of files to be compiled into fast files needs top be reverted which adds the menu files before this change can be bundled with the finished data assets.
